In [1]:
import numpy as np

In [2]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [4]:
a [::-1] 

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [5]:
b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
c= np.array([1,2,0,0,4,0])
c

array([1, 2, 0, 0, 4, 0])

In [7]:
np.nonzero(c)

(array([0, 1, 4], dtype=int64),)

In [8]:
d = np.identity(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
e = np.random.randint(0,100,(3,3,3))
e

array([[[55, 35, 54],
        [54, 81, 41],
        [95, 28, 97]],

       [[25, 97, 41],
        [68, 57, 86],
        [26, 87, 85]],

       [[30, 19, 41],
        [56,  4, 98],
        [41, 45,  2]]])

In [10]:
f = np.random.randint(0,100,(10,10))
f

array([[50, 72,  7,  9, 17, 88, 14, 64,  1, 55],
       [18, 75, 35,  1, 18, 46, 27, 36, 74, 49],
       [11, 11, 31, 15, 22, 30, 38, 12, 10, 49],
       [16, 80, 21,  2, 80, 41, 84,  4, 59, 42],
       [49, 81, 92, 67, 38, 52,  7, 54, 33, 57],
       [24, 22, 11, 38, 81,  2, 86, 11, 54, 68],
       [99, 28, 58, 20, 88, 17, 97, 11, 52, 19],
       [17, 14, 26, 70, 26, 19, 96, 46, 48, 21],
       [83, 34, 15, 63,  4, 49, 18, 90, 66, 39],
       [71, 39, 77, 20, 31, 92, 72, 15, 76, 36]])

In [11]:
f.max()

99

In [12]:
f.min()

1

In [13]:
g = np.random.randint(0,51,(30))
g

array([12,  8, 39, 40,  3,  8, 24, 29, 11, 47, 25, 50, 22, 40, 42, 12,  4,
       30,  6, 18, 45, 45, 22, 14, 45, 43, 43,  1, 33, 20])

In [14]:
g.mean()

26.033333333333335

In [15]:
h = np.ones((5,5))
h

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
h[1:-1,1:-1] = 0
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
i = np.ones((5,5))
i

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False
