In [1]:
import numpy as np


# 1-d Array

In [2]:
one_dim_array = np.array([1,2,3,4,5])

In [3]:
one_dim_array.shape

(5,)

In [4]:
one_dim_array[0]

1

In [5]:
type(one_dim_array)

numpy.ndarray

# np.arrange - creating arrays at specific range (similar to Python range() function)

In [6]:
arr1 = np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [7]:
arr1 = np.arange(10)

In [8]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = np.arange(20,30)

In [10]:
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

# math operations

In [12]:
sample_arr = np.arange(1,6)
sample_arr

array([1, 2, 3, 4, 5])

In [13]:
# Multiplication
sample_arr * 5

array([ 5, 10, 15, 20, 25])

In [14]:
# division
sample_arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

# Indexing

In [15]:
sample_arr2 = np.arange(1,6)
sample_arr2 

array([1, 2, 3, 4, 5])

In [16]:
# get [2,3,4]
sample_arr2[1:-1]

array([2, 3, 4])

In [17]:
sample_arr2 %2 == 0

array([False,  True, False,  True, False])

In [18]:
sample_arr2[sample_arr2 %2 == 0]

array([2, 4])

# 2-D array

In [ ]:
a_two_dim_arr = np.array([[2,2] ])